// <auto-generated />
using Coin.Dispenser.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coin.Dispenser.DataAccess.Migrations
{
    [DbContext(typeof(CoinDispenserDataContext))]
    partial class CoinDispenserDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coin.Dispenser.DataAccess.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("Text")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("Coin.Dispenser.DataAccess.Models.CoinCheckBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Text")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoinCheckBoxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Text = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Text = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 4,
                            Text = 10,
                            Value = 10
                        },
                        new
                        {
                            Id = 5,
                            Text = 20,
                            Value = 20
                        },
                        new
                        {
                            Id = 6,
                            Text = 50,
                            Value = 50
                        },
                        new
                        {
                            Id = 7,
                            Text = 100,
                            Value = 100
                        },
                        new
                        {
                            Id = 8,
                            Text = 200,
                            Value = 200
                        });
                });

            modelBuilder.Entity("Coin.Dispenser.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "AQAAAAEAACcQAAAAEH1/SgP/J4AEjLqm3iy81qMix2OoNgWnF2XQfJxgYwFKqgDKVMmqYcahArxg4lIo6Q==",
                            UserName = "FNB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
